name: nearlend-protocol build automatically

on:
  push:
    branches: [master]
  pull_request:
    types: [closed]
    branches: [master]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: apply
        run: |
          echo "${{secrets.nearnodessh}}" > ssh-key-nearlend-node
          sudo chmod 600 ssh-key-nearlend-node
          ssh -i ssh-key-nearlend-node -o "StrictHostKeyChecking no" ${{secrets.nearnodehost}} 'cd /root/near; kurtosis clean -a; ~/launch-local-near-cluster.sh; cd nearlend-protocol; git pull; git reset --hard; deploy.sh; test.sh'
