name: nearlend-protocol test automatically

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          components: rustfmt, clippy
      # cache for dependencies
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      # linter checks
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args:  --manifest-path ./contracts/Cargo.toml --all -- --check
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args:  --manifest-path ./contracts/Cargo.toml -- -A clippy::too-many-arguments -D warnings

      - run: ./build.sh
      - run: ./test.sh
