name: nearlend-protocol test automatically

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          components: rustfmt, clippy
      # cache for dependencies
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
            contracts/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/contracts/Cargo.lock') }}
      # linter checks
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args:  --manifest-path ./contracts/Cargo.toml --all -- --check
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args:  --manifest-path ./contracts/Cargo.toml -- -A clippy::too-many-arguments -A clippy::ptr-offset-with-cast -A clippy::assign-op-pattern -A clippy::manual-range-contains -D warnings

      - run: ./build.sh
      - run: ./test.sh

  # deployment:
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 150
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions-rs/toolchain@v1
  #       with:
  #         toolchain: stable
  #         target: wasm32-unknown-unknown
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: 14
  #     - name: use near
  #       run: npm install -g near-cli
  #     - name: deploy
  #       run: |
  #         echo "${{secrets.MAIN_NEAR_CLI_PRIVATE_KEY}}" > ${{secrets.MAIN_NEAR_CLI_PRIVATE_KEY_PATH}}
  #         ./deploy.sh --keyPath=${{secrets.MAIN_NEAR_CLI_PRIVATE_KEY_PATH}}
